const DECREMENT = "DECREMENT";
const INCREMENT = "INCREMENT";
const TWODECREMENT = "TWODECREMENT";
const TWOINCREMENT = "TWOINCREMENT";
const SQUARE = "SQUARE";
const SQUAREROOT = "SQUAREROOT";
const RESET = "RESET";


export {DECREMENT, TWODECREMENT, INCREMENT, TWOINCREMENT, SQUARE, SQUAREROOT, RESET}